export const CREATE_TABLE = {
    CT_Material: `CREATE TABLE IF NOT EXISTS CT_Material(
        MaterialName NVARCHAR(200) NOT NULL ,
        Unit NVARCHAR(10) NOT NULL ,
        EXP float(53) NOT NULL DEFAULT ((1)) ,
        Specification NVARCHAR(50) NULL ,
        Remarks NVARCHAR(200) NULL ,
        IsValid bit NOT NULL DEFAULT ((1)) ,
        Pinyin NVARCHAR(50) NOT NULL DEFAULT '' ,
        Attribute NVARCHAR(50) NULL ,
        Imgs NVARCHAR(200) NULL ,
        heat decimal(18,2) NULL ,
        protein decimal(18,2) NULL ,
        fat decimal(18,2) NULL ,
        carbohydrate decimal(18,2) NULL ,
        unitg decimal(18,2) NULL ,
        id VARCHAR(64) PRIMARY KEY NOT NULL ,
        material_type VARCHAR(100) NULL ,
        office_id VARCHAR(64) NULL 
    )`,
    ct_meal: `CREATE TABLE IF NOT EXISTS ct_meal(
        id PRIMARY KEY VARCHAR(64) NOT NULL ,
        factory_id VARCHAR(64) NULL ,
        office_id VARCHAR(64) NULL ,
        meal_type VARCHAR(64) NULL ,
        pre_hour decimal(5,2) NULL ,
        end_hour decimal(5,2) NULL ,
        back_hour decimal(5,2) NULL ,
        is_pre VARCHAR(1) NULL ,
        start_time datetime2(7) NULL ,
        end_time datetime2(7) NULL ,
        del_flag VARCHAR(1) NULL ,
        create_by VARCHAR(64) NULL ,
        create_date datetime2(7) NULL ,
        update_by VARCHAR(64) NULL ,
        update_date datetime2(7) NULL ,
        remarks VARCHAR(200) NULL 
    )`,
    ct_plan: `CREATE TABLE IF NOT EXISTS ct_plan(
        id PRIMARY KEY VARCHAR(64) NOT NULL ,
        meal_id VARCHAR(64) NULL ,
        office_id VARCHAR(64) NULL ,
        start_date datetime2(7) NULL ,
        end_date datetime2(7) NULL ,
        del_flag VARCHAR(1) NULL DEFAULT ((0)) ,
        create_by VARCHAR(64) NULL ,
        create_date datetime2(7) NULL ,
        update_by VARCHAR(64) NULL ,
        update_date datetime2(7) NULL ,
        remarks VARCHAR(200) NULL ,
        status VARCHAR(1) NULL DEFAULT ((0)) 
    )`,
    ct_plan_dtl: `CREATE TABLE IF NOT EXISTS ct_plan_dtl(
        id PRIMARY KEY VARCHAR(64) NOT NULL ,
        plan_id VARCHAR(64) NULL ,
        obj_type VARCHAR(1) NULL ,
        obj_id VARCHAR(64) NULL ,
        price decimal(8,2) NULL ,
        max_num int NULL ,
        chef_id VARCHAR(64) NULL 
    )`,
    ct_product: `CREATE TABLE IF NOT EXISTS ct_product(
        id PRIMARY KEY VARCHAR(64) NOT NULL ,
        product_type VARCHAR(64) NULL ,
        office_id VARCHAR(64) NULL ,
        product_name NVARCHAR(100) NULL ,
        price decimal(18,2) NULL ,
        img_url VARCHAR(1000) NULL ,
        is_score VARCHAR(64) NULL DEFAULT ((0)) ,
        cost_credits decimal(18,2) NULL ,
        create_by VARCHAR(64) NULL ,
        create_date datetime2(7) NULL ,
        update_by VARCHAR(64) NULL ,
        update_date datetime2(7) NULL ,
        remarks NVARCHAR(255) NULL ,
        del_flag char(1) NULL DEFAULT ((0)) ,
        factory_id VARCHAR(64) NULL ,
        labels VARCHAR(1000) NULL ,
        is_hold VARCHAR(1) NULL DEFAULT ((0)) ,
        is_pack VARCHAR(1) NULL DEFAULT ((0)) 
    )`,
    ct_product_dtl: `CREATE TABLE IF NOT EXISTS ct_product_dtl(
        id VARCHAR(64) PRIMARY KEY  NOT NULL ,
        product_id VARCHAR(64) NULL ,
        material_id VARCHAR(64) NULL ,
        weight decimal(18,2) NULL 
    )`,
    ct_product_set: `CREATE TABLE IF NOT EXISTS ct_product_set(
        id PRIMARY KEY VARCHAR(64) NOT NULL ,
        product_set_type VARCHAR(64) NULL ,
        factory_id VARCHAR(64) NULL ,
        office_id VARCHAR(64) NULL ,
        product_set_name VARCHAR(100) NULL ,
        price decimal(8,2) NULL ,
        img_url VARCHAR(500) NULL ,
        is_score VARCHAR(1) NULL DEFAULT ((0)) ,
        cost_credits decimal(8,2) NULL ,
        del_flag VARCHAR(1) NULL DEFAULT ((0)) ,
        create_by VARCHAR(64) NULL ,
        create_date datetime2(7) NULL ,
        update_by VARCHAR(64) NULL ,
        update_date datetime2(7) NULL ,
        remarks VARCHAR(200) NULL ,
        labels VARCHAR(1000) NULL ,
        is_pack VARCHAR(1) NULL DEFAULT ((0)) ,
        is_hold VARCHAR(1) NULL DEFAULT ((0))
    )`,
    ct_product_set_dtl: `CREATE TABLE IF NOT EXISTS ct_product_set_dtl(
        id PRIMARY KEY VARCHAR(64) NOT NULL ,
        product_set_id VARCHAR(64) NULL ,
        product_id VARCHAR(64) NULL ,
        num int NULL ,
        price decimal(8,2) NULL 
    )`,
    sys_dict_type: `CREATE TABLE IF NOT EXISTS sys_dict_type(
        id VARCHAR(64) NULL ,
        type VARCHAR(64) NULL ,
        description NVARCHAR(64) NULL ,
        create_by VARCHAR(64) NULL ,
        create_date datetime2(7) NULL ,
        update_by VARCHAR(64) NULL ,
        update_date datetime2(7) NULL ,
        del_flag VARCHAR(64) NULL ,
        is_selfdom VARCHAR(64) NULL DEFAULT ((0)) ,
        is_sqlite VARCHAR(1) NULL DEFAULT ((0)) 
    )`,
    sys_dict_value: `CREATE TABLE IF NOT EXISTS sys_dict_value(
        id NVARCHAR(64) NULL ,
        dict_type_id NVARCHAR(64) NULL ,
        label NVARCHAR(128) NULL ,
        value NVARCHAR(128) NULL ,
        sort NVARCHAR(64) NULL ,
        create_by NVARCHAR(64) NULL ,
        create_date datetime2(7) NULL ,
        update_by NVARCHAR(64) NULL ,
        update_date datetime2(7) NULL ,
        del_flag NVARCHAR(64) NULL ,
        office_id VARCHAR(64) NULL DEFAULT '' 
    )`,
    sys_office: `CREATE TABLE IF NOT EXISTS sys_office(
        id VARCHAR(64) NULL ,
        parent_id VARCHAR(64) NULL ,
        parent_ids VARCHAR(2000) NULL ,
        name NVARCHAR(100) NULL ,
        sort numeric(10) NULL ,
        area_id VARCHAR(64) NULL ,
        code NVARCHAR(100) NULL ,
        type char(1) NULL ,
        grade nchar(1) NULL ,
        address NVARCHAR(255) NULL ,
        zip_code NVARCHAR(100) NULL ,
        master NVARCHAR(100) NULL ,
        phone NVARCHAR(200) NULL ,
        fax NVARCHAR(200) NULL ,
        email NVARCHAR(200) NULL ,
        USEABLE NVARCHAR(64) NULL ,
        PRIMARY_PERSON NVARCHAR(64) NULL ,
        DEPUTY_PERSON NVARCHAR(64) NULL ,
        create_by NVARCHAR(64) NULL ,
        create_date datetime2(7) NULL ,
        update_by NVARCHAR(64) NULL ,
        update_date datetime2(7) NULL ,
        remarks NVARCHAR(255) NULL ,
        del_flag char(1) NULL  
    )`,
};
export  const INSERT_DATA = {
    // CT_Material: `INSERT INTO CT_Material VALUES(NULL,?,?,?)`,
    ct_meal: ``,
    ct_plan: ``,
    ct_plan_dtl: ``,
    ct_product: ``,
    ct_product_dtl: `INSERT INTO ct_product_dtl VALUES(?,?,?,?)`,
    ct_product_set: ``,
    ct_product_set_dtl: ``,
    sys_dict_type: ``,
    sys_dict_value: ``,
    sys_office: ``,
};